### ISSUE TITLE
Height map generated image does not import into Unreal at sea level Z=0

### ISSUE THREAD

**Issue by delebash** [delebash/unreal_mapbox_bridge#7]
Using the formula from Mapbox to calculate height `elevation = -10000 + (({R} * 256 * 256 + {G} * 256 + {B}) * 0.1)`  causes the map to import way below sea level.  Even if you change the Unreal Landscape Z transform to 0 it really does not change the actual elevation.  This can be demonstrated by changing the landscape Z transform to 0.  Then place an actor such as a mannequin on the landscape.  You will notice that the actor's location is showing the original location way below sea level.  I manually adjusted the formula to try and compensate.  It is better but of course but not accurate.  Also, the 16bit image is now grey instead of B+W but the features still import correctly.

**Comment by colkassad** [comment]
Is it related to this?: https://docs.unrealengine.com/4.27/en-US/BuildingWorlds/Landscape/TechnicalGuide/#calculatingheightmapzscale

**Comment by delebash** [comment]
I am not sure.  I the above formula to calculate the Z scale.  Here is a video showing the problem.  https://1drv.ms/v/s!Aq4OgSZRh__uieNLDnjytI0m9hf5WA?e=fdX9at

**Comment by colkassad** [comment]
A few things I found:

https://forums.unrealengine.com/t/what-is-unreal-unit-height-translation-after-importing-16bit-heightmap-to-level/157062

https://old.reddit.com/r/unrealengine/comments/li6xmi/ue_426_water_plugin_with_heighthmaps/

Not the best information. This person seems to have the same problem: https://stackoverflow.com/questions/70222487/how-do-you-reset-an-unreal-engine-4-5-landscape-back-to-0-z-height-or-sea-level

..but no answers :(

Perhaps you need to translate the elevations somehow, e.g. finding the center elevation in your range and adding that to all of your heightmap elevation values before import. Or just noting that value and adding it to your transform when placing it in the map. Try noting where a few heightmaps gets placed in the Z and compare with your elevation ranges to see if a pattern emerges (long shot, especially with the Z scaling involved).

Btw, I tried opening your plugin but had some issues with dependencies. Probably my lack of knowledge dealing with custom plugins.

**Comment by colkassad** [comment]
> Perhaps you need to translate the elevations somehow, e.g. finding the center elevation in your range and adding that to all of your heightmap elevation values before import. Or just noting that value and adding it to your transform when placing it in the map.

You'll probably need to incorporate your z-scaling into this calculation as well. I'd try to work it out for you but I'm pretty terrible with math :)

**Comment by colkassad** [comment]
I'd probably start with testing something like:

z transform value = ((z transform value) + 32768) * (z scale value)

**Comment by delebash** [comment]
Are you on Windows?

**Comment by colkassad** [comment]
I am, yes. I'll try to submit a proper issue today.

**Comment by delebash** [comment]
Cool!  Currently I am just writing the coordinates to the output log.  Then I add a few cubes on the landscape and set them to those coordinates to see how they look.  To show the output log go to Windows/Developer Tools and select output log.  Before running the import process right click on the output log window and choose clear.  This just makes it easier to see the resulting coordinates.

**Comment by delebash** [comment]
The id field under geometry in your geojson is what I am looking at to parse the data.

**Comment by delebash** [comment]
> > Perhaps you need to translate the elevations somehow, e.g. finding the center elevation in your range and adding that to all of your heightmap elevation values before import. Or just noting that value and adding it to your transform when placing it in the map.
> 
> You'll probably need to incorporate your z-scaling into this calculation as well. I'd try to work it out for you but I'm pretty terrible with math :)

I am much worse with math than you.  You made all the lon/lat calc's for creating the heightmap so you are much better at it than I am.  What you did really helped me understand what was going on.

I am not sure I understand what you are talking about when you say incorporate your Z-scaling.

I tried adding the median elevations to all the elevations values in the array, but I still have the same problem.  Also, the X and Y are not centered.  I expect we need to fix this problem with the heghtmap before we can import the geojson correctly.  What do you think?

**Comment by delebash** [comment]
Tested Gae, World Machine, and World Creator.  All of these programs heightmap had the same import problem.  The landscape Z transform showed 100 but a cube actor placed on the landscape was always in the high negative range.

**Comment by colkassad** [comment]
I'm out of town for awhile but will try to experiment when I get back.

**Comment by delebash** [comment]
Cool, have a safe trip.

**Comment by delebash** [comment]
More information about the problem:

<img width="960" alt="UnrealEditor_VE6zJyMfse" src="https://user-images.githubusercontent.com/2220160/151216108-da267dfe-e074-49a5-9213-cc15bea70ea5.png">

This image is a picture of the imported landscape heightmap for Mt. Rainier.  If you look at the hole this is as far down as the sculpting tool would let me dig.  You will notice the cube Z position in that hole is --25500.0.  So with the height range of 255 to -255 the landscape is importing almost at the bottom of the range.  

1) How do we find the sea level of a heightmap?



2) How do we adjust the heightmap so it will import into Unreal correctly?

If we cannot adjust the sea level, then we cannot make sculpt deep Canyons or Rivers with the imported landscape.

**Comment by delebash** [comment]
Further testing:

I created a new blank 2017x2017 landscape in Unreal.  I sculpted so height features and then exported the heightmap from Unreal to png.  Below is the resulting image
![sixteen-9-82-180-2017](https://user-images.githubusercontent.com/2220160/151650515-d320bd1e-36e6-4379-8ff9-54618fe9730a.png)

1) What is Unreal using as it's color scale since this image is grey for land at sea level instead of Black and White?

**Comment by delebash** [comment]
More Testing:

I compared the min max height of a new landscape hieghtmap to the one created by the web application

The Unreal min/max  is 
32768
43267


The webapp min/max for Mt. Rainier is
104
4381


The web app is using this formula from mapbox to convert the encoded elevation rgb data to meters
-10000 + ((r * 256 * 256 + g * 256 + b) * 0.1)

This data 4381 is the correct elevation in meters for Mt. Rainier.

How do we convert these numbers  to the Unreal numbers? 

Is Unreal using the 65,536 range for 16bit?  
So we should not convert it to meters?

**Comment by delebash** [comment]
This guy was having the same problem.  Note for further exploration     https://forums.unrealengine.com/t/what-is-unreal-unit-height-translation-after-importing-16bit-heightmap-to-level/157062/6

**Comment by delebash** [comment]
I believe I have fixed the sea level issue by scaling the image using gdal js.      '-scale', minelevation, maxelevation, '32768', '65535',
I got this info from this question on unreal forums.  The only problem is re-calculating Z scale which I am not getting correct.

https://forums.unrealengine.com/t/what-is-unreal-unit-height-translation-after-importing-16bit-heightmap-to-level/157062/5

Text for future reference:

> 
> Starting from [SRTM 1](https://www2.jpl.nasa.gov/srtm/) image:
> gdalwarp -co “COMPRESS=LZW” -r near -t_srs “EPSG:31983” S20W044.hgt S20W044.tif
> To bring data values to a suitable orthogonal projection. Open image, select and clip some desired area. I selected some 505px x 505px (15150m x 15150m) area to have image exact size one of the recommended UE sizes. Then write down min max image pixel values (heights), for me is 683 ~ 1370.
> Then
> gdal_translate -ot UInt16 -scale 683 1370 32768 65535 S20W044_1.tif S20W044.png
> This scale up pixel values to full range (of half space for Z - from 0 to 255.992 in UE). Also save it as 16bit unsigned, just to have image in same shape of ones exported from UE levels.
> Spatial resolution (cell size) of SRTM is 30, so the real size is 505*30=15150m. The new scale for X Y is 15150/505=30x the size of actual scale=3000.
> For Z scale, the real world height amplitude from the SRTM clip is 68600cm, and actual amplitude in uu is 256, so 68600/256=270.703 for Z scale.
